include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v8.0.0/templates/scala.yml'

test sbt-datadog:
  extends: .sbt-test
  tags: []

unused-dependencies:
  extends: .sbt-unused-dependencies
  tags: []

version:
  extends: .version
  tags: []
  image:
    name: colisweb/semantic-release:0.10.2
    entrypoint: []

publish on bintray:
  extends: .bintray-publish
  tags: []

