include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v7.7.1/templates/scala.yml'

compile:
  extends: .sbt-compile
  tags: []

test sbt-datadog:
  extends: .sbt-test
  tags: []

version:
  extends: .version
  tags: []

publish on bintray:
  extends: .bintray-publish
  tags: []


