include:
  - 'https://colisweb-open-source.gitlab.io/ci-common/v13.12.0/templates/scala.yml'

test sbt-datadog:
  extends: .sbt-test
  tags:
    - aws

version sbt-datadog:
  extends: .version
  tags:
    - aws

publish sbt-datadog:
  extends: .sonatype-publish
  tags:
    - aws
